name: where
version: 5.0.0

author: CÃ©dric Belin <cedric@belin.io>
description: Find the instances of an executable in the system path.
documentation: https://dev.belin.io/where.dart/api
homepage: https://dev.belin.io/where.dart

environment:
  sdk: '>=2.0.0-dev.64 <2.0.0'

executables:
  where: where

dependencies:
  args: ^1.4.3
  path: ^1.6.1
  yaml: ^2.1.14

dev_dependencies:
  coverage: ^0.11.0
  grinder: ^0.8.2
  test: ^0.12.42
